# Generated by Django 6.0.6 on 2026-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_linkproyecto_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
