# Generated by Django 6.0.6 on 2026-07-21 12:15

import django.db.models.deletion
import proyectos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_fecha_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=proyectos.models.generar_codigo_invitacion, editable=False, max_length=10, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usada', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='proyectos.proyecto')),
                ('usada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_usadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
